import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { resolve } from 'path';
import { writeFileSync, readFileSync } from 'fs';
import { transformSync } from 'esbuild';

const root = process.cwd();

// 稳健读取 modules.config.ts：用 esbuild 转译后求值，避免手搓正则漏匹配嵌套结构
const cfgSrc = readFileSync(resolve(root, 'modules.config.ts'), 'utf-8');
const cfgJs = transformSync(cfgSrc, { loader: 'ts', format: 'cjs' }).code;
const sandbox: any = { module: { exports: {} }, exports: {} };
new Function('module', 'exports', cfgJs)(sandbox.module, sandbox.module.exports);
const buildConfig: any = sandbox.module.exports.buildConfig || {};

// 解析本次构建要启用的模块（优先级从高到低）：
//   1) MODULE_IDS 环境变量（逗号分隔模块 id，交互式/自定义打包用，如 MODULE_IDS=excel-copy,quick-note）
//   2) MODULE_PROFILE 环境变量命中的预设（构建时灵活覆盖）
//   3) 文件中的 profile 字段命中的预设
//   4) enabledModules 兜底
const profileName = process.env.MODULE_PROFILE || buildConfig.profile || 'standard';
const rawIds = (process.env.MODULE_IDS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);
const enabled: string[] = rawIds.length
  ? rawIds
  : (buildConfig.profiles && buildConfig.profiles[profileName]) ||
    buildConfig.enabledModules ||
    [];

console.log(`[vite] build profile="${profileName}" modules=[${enabled.join(', ')}]`);

// 根据启用清单生成 registry.generated.ts
// 关键点：生成文件只 import enabledModules 中的 meta 与 index，
// 因此未启用的业务模块不会出现在源码引用链中 → 不进入 bundle（构建期裁剪）
const varName = (id: string) => id.replace(/-/g, '');
const metaImports = enabled
  .map((id) => `import * as ${varName(id)} from '@/modules/${id}/meta';`)
  .join('\n');
const metaArr = enabled.map((id) => `${varName(id)}.meta`).join(', ');
const loaders = enabled
  .map((id) => `  '${id}': () => import('@/modules/${id}/index'),`)
  .join('\n');

const generated = `// AUTO-GENERATED by vite.config.ts — do not edit.
${metaImports}
export const enabledModuleMetas = [${metaArr}];
export const moduleViewLoaders: Record<string, () => Promise<any>> = {
${loaders}};
`;

writeFileSync(resolve(root, 'src/registry.generated.ts'), generated);

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': resolve(root, 'src'),
    },
  },
  base: './',
  build: {
    outDir: 'dist/renderer',
    emptyOutDir: true,
  },
  server: {
    port: 5173,
  },
});
