import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { resolve } from 'path';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { transformSync } from 'esbuild';

const root = process.cwd();

// 模块源码双根解析：
//   - src/modules/<id>/      —— 常规内建业务模块（保留 modules 机制）
//   - extensions/<id>/src/   —— 随宿主分发的视图插件包（kind=view，构建期随包编译）
// 物理外置后 excel-copy / order-insight 走 extensions 根；quick-note 等仍在 src/modules。
const MODULE_ROOTS = [
  { kind: 'modules' as const, probe: (id: string) => `src/modules/${id}/meta.ts` },
  { kind: 'extensions' as const, probe: (id: string) => `extensions/${id}/src/meta.ts` },
];

function resolveModuleRoot(id: string): string | null {
  for (const r of MODULE_ROOTS) {
    if (existsSync(resolve(root, r.probe(id)))) return r.kind;
  }
  return null;
}

/** registry 内 import 前缀（registry 位于 src/，extensions 用相对路径跳出 src 指向根/extensions） */
const importPrefix = (kind: string) => (kind === 'modules' ? '@/modules/' : '../extensions/');

// 稳健读取 modules.config.ts：用 esbuild 转译后求值，避免手搓正则漏匹配嵌套结构
const cfgSrc = readFileSync(resolve(root, 'modules.config.ts'), 'utf-8');
const cfgJs = transformSync(cfgSrc, { loader: 'ts', format: 'cjs' }).code;
const sandbox: any = { module: { exports: {} }, exports: {} };
new Function('module', 'exports', cfgJs)(sandbox.module, sandbox.module.exports);
const buildConfig: any = sandbox.module.exports.buildConfig || {};

// 解析本次构建要启用的模块（优先级从高到低）：
//   1) MODULE_IDS 环境变量（逗号分隔模块 id，交互式/自定义打包用，如 MODULE_IDS=excel-copy,quick-note）
//   2) MODULE_PROFILE 环境变量命中的预设（构建时灵活覆盖）
//   3) 文件中的 profile 字段命中的预设
//   4) enabledModules 兜底
const profileName = process.env.MODULE_PROFILE || buildConfig.profile || 'standard';
const rawIds = (process.env.MODULE_IDS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);
const enabled: string[] = rawIds.length
  ? rawIds
  : (buildConfig.profiles && buildConfig.profiles[profileName]) ||
    buildConfig.enabledModules ||
    [];

console.log(`[vite] build profile="${profileName}" modules=[${enabled.join(', ')}]`);

// 根据启用清单生成 registry.generated.ts
// 关键点：生成文件只 import enabledModules 中的 meta 与 index，
// 因此未启用的业务模块不会出现在源码引用链中 → 不进入 bundle（构建期裁剪）
const varName = (id: string) => id.replace(/-/g, '');
const roots: Record<string, string> = {};
for (const id of enabled) {
  const r = resolveModuleRoot(id);
  if (!r) {
    console.error(`[vite] ⚠ module/plugin "${id}" not found in src/modules or extensions/<id>/src — skipped`);
    continue;
  }
  roots[id] = r;
}
const active = enabled.filter((id) => roots[id]);
/** 模块/插件包入口路径：extensions 根为 extensions/<id>/src/<file>，src/modules 根为 src/modules/<id>/<file> */
const entryPath = (id: string, file: string) => {
  const isExt = roots[id] === 'extensions';
  return `${isExt ? '../extensions/' : '@/modules/'}${isExt ? `${id}/src` : id}/${file}`;
};
const metaImports = active
  .map((id) => `import * as ${varName(id)} from '${entryPath(id, 'meta')}';`)
  .join('\n');
const metaArr = active.map((id) => `${varName(id)}.meta`).join(', ');
const loaders = active
  .map((id) => `  '${id}': () => import('${entryPath(id, 'index')}'),`)
  .join('\n');

// —— 随宿主分发视图插件包的元数据（读取 extensions/<id>/manifest.json；src/modules 内建无条目）——
// 供 PluginCenter/overview 展示版本、描述与作者。
const pkgLines = active
  .filter((id) => roots[id] === 'extensions')
  .map((id) => {
    try {
      const m = JSON.parse(readFileSync(resolve(root, `extensions/${id}/manifest.json`), 'utf-8'));
      const extra = [
        m.description ? `description: ${JSON.stringify(m.description)}` : '',
        m.author ? `author: ${JSON.stringify(m.author)}` : '',
      ]
        .filter(Boolean)
        .join(', ');
      return `  '${id}': { version: ${JSON.stringify(m.version || '0.0.0')}${extra ? `, ${extra}` : ''} },`;
    } catch (e: any) {
      console.warn(`[vite] manifest parse failed for extensions/${id}/manifest.json`, e?.message);
      return '';
    }
  })
  .filter(Boolean);

// —— 插件包设置面板入口（settings.ts 存在才生成 loader；SettingsModal 分类导航按此贡献驱动）——
const settingsLoaderLines = active
  .filter(
    (id) =>
      roots[id] === 'extensions' &&
      existsSync(resolve(root, `extensions/${id}/src/settings.ts`)),
  )
  .map((id) => `  '${id}': () => import('${importPrefix('extensions')}${id}/src/settings'),`)
  .join('\n');

const generated = `// AUTO-GENERATED by vite.config.ts — do not edit.
${metaImports}
export const enabledModuleMetas = [${metaArr}];
export const moduleViewLoaders: Record<string, () => Promise<any>> = {
${loaders}};

// 随宿主分发视图插件包元数据（extensions/<id>/manifest.json；src/modules 内建无条目）
export const pluginPackageInfos: Record<string, { version: string; description?: string; author?: string }> = {
${pkgLines.length ? pkgLines.join('\n') : '  // (none)'}
};

// 设置面板入口（插件包 src/settings.ts；无设置面板的插件无条目）
export const settingsPanelLoaders: Record<string, () => Promise<any>> = {
${settingsLoaderLines ? settingsLoaderLines : '  // (none)'}};
`;

writeFileSync(resolve(root, 'src/registry.generated.ts'), generated);

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': resolve(root, 'src'),
    },
  },
  base: './',
  build: {
    outDir: 'dist/renderer',
    emptyOutDir: true,
  },
  server: {
    port: 5173,
  },
});
